Транзакции
mospolytech-finapp/web pull request #37
Opened 2023-05-08 01:19 UTC by Sh1mpi

## Описание изменений

Добавлена страница транзакций , сделан адаптив, кнопки добавление, подробнее, удалить работают

## Тестирование

перейти в **/transactions** 

## Проверка кода

проверьте удобно ли все сделано для передачи данных с бека

## Дополнительная информация

советую проверить адаптив, переполнение, кнопки

2023-05-09 13:35 UTC, DimDimich-creator requested changes
Сделай исправления и подождем еще ревью от @dangannn и еще предстоит соединить с бэком

2023-05-09 13:35 UTC, DimDimich-creator commented on src/components/Transactions.tsx
> +            label: 'Категория',
ни один `label` не работает когда по нему нажимаешь

2023-05-09 13:35 UTC, DimDimich-creator commented on src/components/ui/modals/ModalTransactions.tsx
> +                type={'text'}
Для времени есть специальный тип [time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time)

2023-05-09 13:35 UTC, DimDimich-creator commented on src/components/ui/modals/ModalTransactions.tsx
> +                type={'text'}
Для чисел есть специальный тип [number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)

2023-05-09 13:35 UTC, DimDimich-creator commented on src/components/ui/modals/ModalTransactions.tsx
> +                id={'date'}
В некоторых `inputs` повторяются `name` и `id`

2023-05-09 13:35 UTC, DimDimich-creator commented on src/components/ui/Select.tsx
> +  }
[про хуки и классы](https://medium.com/sibdev/в-прошлом-году-react-получил-глобальное-нововведение-hooks-или-хуки-d52b6502224d)
```jsx
const togglePasswordVisibility = (e: React.MouseEvent<HTMLButtonElement>) => {
  e.preventDefault()
  e.stopPropagation()
  setIsPasswordVisible((prevState) => !prevState)
}
```

2023-05-09 13:35 UTC, DimDimich-creator commented on src/components/ui/Select.tsx
> +  disabled?: true
`disabled?: boolean`

2023-05-09 13:35 UTC, DimDimich-creator commented on src/components/Transactions.tsx
стрелочка поехала
![image](https://github.com/mospolytech-finapp/web/assets/59178589/fe17d8f6-4494-4a0d-97de-bc3bc0eb6c2d)

![image](https://github.com/mospolytech-finapp/web/assets/59178589/2c8ac822-dd7e-47e7-a832-05b9343582db)
(так на макете)

2023-05-09 13:35 UTC, DimDimich-creator commented on src/components/Transactions.tsx
а где проверка на типы?

2023-05-09 14:33 UTC, Sh1mpi commented on src/components/ui/Select.tsx
> +  }
я просто удалю это, потому что в Select это не используется

2023-05-10 10:08 UTC, DimDimich-creator approved these changes

2023-05-10 15:29 UTC, f1xgun requested changes

2023-05-10 15:29 UTC, f1xgun commented on src/components/Transactions.tsx
> +          </Button>
Дизайн кнопок немного другой
![image](https://github.com/mospolytech-finapp/web/assets/88651829/c23fab76-d228-490d-ab30-ee1228890911)
![image](https://github.com/mospolytech-finapp/web/assets/88651829/6d0dfb75-c000-422e-80fe-2e3ea28bdc3d)

2023-05-10 15:29 UTC, f1xgun commented on src/components/Transactions.tsx
мне кажется, что лучше в placeholder в модальном окне modaltransactions передавать значения транзакции, на которой мы нажали кнопку "Подробнее"

2023-05-10 15:29 UTC, f1xgun commented on src/components/ui/modals/ModalTransactions.tsx
> +                <div className="mb-2 flex w-24 flex-col sm:w-32">
на маленьких экранах инпуты "От", "До" становятся меньше чем "Дата" и "Время" из-за того, что первые имеют ширину w-24, а вторые w-32

2023-05-10 15:29 UTC, f1xgun commented on src/components/ui/modals/ModalTransactions.tsx
Инпуты становятся очень маленькими при экране меньше 768px
![image](https://github.com/mospolytech-finapp/web/assets/88651829/0fbe1fb2-125b-4e69-b853-9092041755f0)

2023-05-10 15:29 UTC, f1xgun commented on src/components/ui/modals/ModalInputsBtns.tsx
> +import crossIcon from '../../../assets/images/cross.svg'
Необходимо использовать black_cross.svg

2023-05-10 15:29 UTC, f1xgun commented on src/components/Transactions.tsx
> +          <img alt="параметры" className="mt-3" src={settings_img} />
Слишком большая иконка "шестеренки" на маленьких экранах, в макете она становится меньше

2023-05-10 15:29 UTC, f1xgun commented on src/components/Transactions.tsx
Необходимо поправить хедер транзакций для правильного адаптива в соответствии с макетом

2023-05-10 21:38 UTC, Sh1mpi commented on src/components/Transactions.tsx
свяжи с беком сначала, потом я сделаю чтобы это передавалось как props, иначе придется два раза исправлять , этот pr это шаблон транзакций

2023-05-10 21:44 UTC, Sh1mpi commented on src/components/Transactions.tsx
> +          </Button>
у нас есть компоненты кнопок которые легко использовать везде, а тут велосипед предлагают сделать, зачем исправлять кнопки как на макете в хедере транзакций, если на всем сайте кнопки по другому выглядят, это на первых парах проектирования сайтов объясняли, что все должно быть в 1 стиле

2023-05-10 21:47 UTC, Sh1mpi commented on src/components/Transactions.tsx
> +          <img alt="параметры" className="mt-3" src={settings_img} />
если оставляем компонентные кнопки, то из-за flex-row она в своем размере помещается, если уменьшить , то будет выглядить плохо
![image](https://github.com/mospolytech-finapp/web/assets/59705273/0e4a8a82-f136-4bda-aefb-dbebea31897c)

2023-05-10 21:50 UTC, Sh1mpi commented on src/components/Transactions.tsx
тоже самое, из-за кнопок , если оставим так, то они либо не влезают либо ультра меленькие, Дима одобрил что дизайн хуйня

2023-05-11 07:44 UTC, f1xgun approved these changes

2023-05-11 07:45 UTC, merged